create table if not exists public.quiz_scores (
  id bigint generated by default as identity primary key,
  quiz_version text not null,
  name text not null,
  score integer not null check (score between 0 and 100),
  correct_count integer not null,
  total_questions integer not null,
  created_at timestamptz not null default now()
);

alter table public.quiz_scores enable row level security;

drop policy if exists "quiz_scores_public_select" on public.quiz_scores;
create policy "quiz_scores_public_select"
on public.quiz_scores for select
to anon
using (quiz_version = 'nha-trang-quiz-2');

drop policy if exists "quiz_scores_public_insert" on public.quiz_scores;
create policy "quiz_scores_public_insert"
on public.quiz_scores for insert
to anon
with check (
  quiz_version = 'nha-trang-quiz-2'
  and char_length(trim(name)) between 1 and 20
  and score between 0 and 100
  and correct_count between 0 and 20
  and total_questions = 20
);

grant select, insert on table public.quiz_scores to anon;
grant usage, select on sequence public.quiz_scores_id_seq to anon;
